# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
<br/><i> Binggung Dengan Pembayaran💳 Bayar Di 👇 aja<i/>
<script src="https://www.paypal.com/sdk/js?client-id=sb"></script>
<script>paypal.Buttons().render('body');</script><br/>
https://ad.atdmt.com/c/img;adv=11162240857546;ec=11162243355720;adv.a=%eadv!;c.a=%ebuy!;s.a=%esid!;p.a=%epid!;a.a=%eaid!;cache=%n;qpb=1;?h=
